name: Run JavaScript in GitHub Actions

on:
    push:
        branches: [main]
env:
    TEMPLATE_FILE: template.yaml
    SAM_CLI_TELEMETRY: 0

permissions:
    id-token: write
    contents: read

jobs:
    s3ls:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - uses: aws-actions/setup-sam@v2
              with:
                  use-installer: true

            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: "ap-northeast-1" # リージョンを指定
                  role-to-assume: "arn:aws:iam::058264266727:role/oicd-actions" # 作成した IAM ロールの ARN

            #  buildとdeployを実行
            - run: sam build
            - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
