name: Run JavaScript in GitHub Actions

on:
    push:
        branches:
            - main

jobs:
    setup_and_run_script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: pnpm install

            - name: Run script
              run: node index.js
